---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: registry.redhat.io/ansible-automation-platform-23/ee-minimal-rhel8:latest
  EE_BUILDER_IMAGE: registry.redhat.io/ansible-automation-platform-23/ansible-builder-rhel8:latest

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

additional_build_steps:
  prepend: |
    RUN pip3 install --upgrade pip setuptools
  append: |
    COPY ca.cert.pem /etc/pki/ca-trust/source/anchors/ca.cert.pem
    RUN update-ca-trust
    RUN update-crypto-policies --set DEFAULT:AD-SUPPORT
